# Generated by Django 5.0.4 on 2024-08-18 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "privacy",
                    models.BooleanField(
                        default=False, verbose_name="Datenschutzerklärung"
                    ),
                ),
                (
                    "disclaimer",
                    models.BooleanField(
                        default=False, verbose_name="Haftungsausschluss"
                    ),
                ),
                (
                    "terms",
                    models.BooleanField(
                        default=False, verbose_name="Nutzungsrichtlinien"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
        ),
    ]
