# Generated by Django 5.0.4 on 2024-09-02 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blocked",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blocked",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Blockiert",
                    ),
                ),
                (
                    "friends",
                    models.ManyToManyField(
                        blank=True,
                        related_name="friends_with",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Freunde",
                    ),
                ),
                (
                    "received_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erhaltene Anfragen",
                    ),
                ),
                (
                    "sent_requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Gesendete Anfragen",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
        ),
    ]
