# Generated by Django 5.0.4 on 2024-09-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_create_social_users_for_existing_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Moderator", "Moderator"),
                            ("Premium", "Premium"),
                            ("Verifiziert", "Verifiziert"),
                            ("Standard", "Standard"),
                        ],
                        max_length=50,
                        verbose_name="Rolle",
                    ),
                ),
                ("stufe", models.IntegerField(verbose_name="Stufe")),
            ],
        ),
    ]
