# Generated by Django 5.0.4 on 2024-09-19 20:08

from django.db import migrations


def assign_default_role(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Role = apps.get_model("system", "Role")
    ConfigUser = apps.get_model("system", "ConfigUser")

    standard_role, created = Role.objects.get_or_create(name="Standard", priority=1)

    for user in User.objects.all():
        ConfigUser.objects.get_or_create(user=user, defaults={"role": standard_role})


def remove_assigned_roles(apps, schema_editor):
    ConfigUser = apps.get_model("system", "ConfigUser")

    ConfigUser.objects.update(role=None)


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0005_rename_stufe_role_priority_configuser"),
    ]

    operations = [
        migrations.RunPython(assign_default_role, remove_assigned_roles),
    ]
