# Generated by Django 5.0.4 on 2024-10-10 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0006_assign_default_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Benutzer",
            ),
        ),
    ]
