# Generated by Django 5.0.4 on 2024-10-27 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0007_alter_configuser_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Warning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ABUSE", "Missbrauch von Privilegien"),
                            ("ANTISEMITISM", "Antisemitismus"),
                            ("BLACKMAILING", "Erpressung"),
                            ("BULLYING", "Cybermobbing"),
                            ("CHRISTOPHOBIA", "Christophobie"),
                            ("COW", "Unangemessene Wortwahl"),
                            ("DISCRIMINATION", "Diskriminierung"),
                            ("DOXXING", "Doxxing"),
                            ("EXPLOITATIVE_CONTENT", "Ausbeuterische Inhalte"),
                            ("FASCISM", "Faschismus"),
                            ("GROOMING", "Cybergrooming"),
                            ("HARASSMENT", "Belästigung"),
                            ("HATESPEECH", "Hassrede"),
                            ("HOMOPHOBIA", "Homophobie"),
                            ("ILLEGAL_CONTENT", "Illegale Inhalte"),
                            ("ISLAMOPHOBIA", "Islamophobie"),
                            ("MISINFORMATION", "Falschinformationen"),
                            ("PROPAGANDA", "Propaganda"),
                            ("RACISM", "Rassismus"),
                            ("RELATIVISATION", "Relativierung"),
                            ("SCAM", "Betrug"),
                            ("SEXISM", "Sexismus"),
                            ("SPAM", "Spam"),
                            ("SWEARWORD", "Beleidigung"),
                            ("THREAT", "Drohung"),
                            ("VIOLENT_CONTENT", "Gewaltbasierter Inhalt"),
                            ("WHATABOUTISM", "Whataboutismus"),
                            ("XENOPHOBIA", "Fremdenfeindlichkeit"),
                        ],
                        default="ABUSE",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="warned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "author"],
            },
        ),
    ]
