# Generated by Django 5.0.4 on 2024-08-19 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="hex",
        ),
    ]
