# Generated by Django 5.0.4 on 2024-08-25 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0002_remove_category_hex"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Einkaufsliste")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_lists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geteilt mit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Menge")),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("g", "Gram"),
                            ("mg", "Milligram"),
                            ("l", "Liter"),
                        ],
                        default="kg",
                        max_length=2,
                        verbose_name="Einheit",
                    ),
                ),
                (
                    "unit_per_item",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Einheit pro Stück",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_done", "Nicht erledigt"),
                            ("in_progress", "In Bearbeitung"),
                            ("done", "Erledigt"),
                        ],
                        default="not_done",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.food",
                        verbose_name="Nahrung",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.shoppinglist",
                        verbose_name="Einkaufsliste",
                    ),
                ),
            ],
        ),
    ]
