# Generated by Django 5.0.4 on 2024-08-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0004_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="color",
            field=models.CharField(
                choices=[
                    ("gray", "Grau"),
                    ("red", "Rot"),
                    ("orange", "Orange"),
                    ("yellow", "Gelb"),
                    ("green", "Grün"),
                    ("cyan", "Türkis"),
                    ("blue", "Blau"),
                    ("purple", "Violett"),
                ],
                default="gray",
                max_length=10,
                verbose_name="Farben",
            ),
        ),
    ]
