# Generated by Django 5.0.4 on 2024-09-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0006_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglistitem",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Status"),
        ),
    ]
