# Generated by Django 5.0.4 on 2024-09-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0008_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglistitem",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kg", "Kilogram"),
                    ("g", "Gram"),
                    ("mg", "Milligram"),
                    ("l", "Liter"),
                ],
                default="",
                max_length=2,
                null=True,
                verbose_name="Einheit",
            ),
        ),
        migrations.AlterField(
            model_name="shoppinglistitem",
            name="unit_per_item",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1,
                max_digits=10,
                null=True,
                verbose_name="Einheit pro Stück",
            ),
        ),
    ]
